### ISSUE TITLE
Possible merger of custom-elements plugin

### ISSUE THREAD

**Issue by 43081j** [43081j/eslint-plugin-wc#82]
We may be merging the custom-elements eslint plugin's extra functionality into this plugin so we can maintain one together.

To do that, we need to:

- Create or copy across any additional rules this plugin doesn't already have
- Update or replace rules we have with their better counterparts (for the ones which are better)

That also means this'll be a breaking change (or many).

Plugin can be found [here](https://github.com/github/eslint-plugin-custom-elements/tree/main).

## CE rules

- Require `customElements.define` calls to be _after_ class definitions
- Expose registered classes in the global namespace (`window`)
- Require that defined elements extend the correct super class (e.g. `HTMLElement`)
- Require that the filename matches the element name
- Disallow use of the constructor (_entirely_, in that this isn't the same as `wc/no-constructor-params` and friends)
- Disallow extending built in elements
- Disallow DOM traversal in `attributeChangedCallback`
- Disallow DOM traversal in `connectedCallback`
- Disallow any non-element export in a file containing an exported element
- Disallow `on` as a prefix for methods
- Require `customElements.define` calls to be guarded
- Disallow multiple element definitions per file
- Require tag name to match class name (i.e. convert camel to kebab case)
- Require valid tag names

### `wc/no-invalid-element-name` (DONE)

This one is slightly less robust than the CE rule, so we should add the following functionality:

- `options.onlyAlphanum` - only allow alpha-numeric names
- `options.disallowNamespaces` - disallow well known namespaces
- `options.suffix` - require a suffix on all names
- `options.prefix` - require a prefix on all names

Currently, we have a `options.loose` flag which is the equivalent of setting `options.disallowNamespaces` to `false`.

~For backwards compat, we should probably deprecate `loose` but alias it to `!disallowNamespaces`~

This backwards compat was discarded since its a breaking change either way here.

## New rules

- [x] `wc/define-tag-after-class-definition` #84 
- [x] `wc/expose-class-on-global` #85 
- [x] `wc/extends-correct-class` #96 
- [x] `wc/file-name-matches-element` #97 
- [x] `wc/no-customized-built-in-elements` #87
- [x] `wc/no-dom-traversal-in-attributechangedcallback` #88
- [x] `wc/no-dom-traversal-in-connectedcallback` #89
- [x] `wc/no-exports-with-element` #94 
- [x] `wc/no-method-prefixed-with-on` #92
- [x] `wc/no-unchecked-define` #93 
- [x] `wc/one-element-per-file` #90
- [x] `wc/tag-name-matches-class` #91
- [x] `wc/no-constructor` #86 

## Open questions

- Do we want to rename `no-unchecked-define` to follow eslint's naming, and call it `guard-define-call`? (e.g. they have `guard-for-in`, and we have `guard-super-call`)

cc @keithamus @stramel

**Comment by 43081j** [comment]
just an update mostly for @keithamus

i've added most of the rules, but no docs yet (your docs are well written so it may make sense to just copy those across).

also, some code might seem more complex because i've used type narrowing rather than esquery selectors when dealing with finding elements, define calls, etc.

reason for this is mostly consistency _for now_. and if it makes more sense / cleaner code to have a selector instead, we can do it in all places rather than one (e.g. one pr for changing all `define` call lookups to a selector could make sense in future).

**Comment by keithamus** [comment]
Happy to migrate the docs across. I've no concerns about the code differences.

**Comment by 43081j** [comment]
@keithamus now that we have all the rules, could you possibly help me move docs over? we should review them rather than do a straight copy though, as some rules changed name and some may differ slightly in options.

if you get any time, just let me know which rules and i'll try pick up some others

**Comment by keithamus** [comment]
For sure!

**Comment by 43081j** [comment]
![end is near](https://media.tenor.com/pioJTCSFe78AAAAC/the-simpsons-homer.gif)

all docs are complete! we just need to update the main readme now, do some double checking, and ill get a pre-release published so we can try it out

**Comment by 43081j** [comment]
I've published [2.0.0-ce.0](https://www.npmjs.com/package/eslint-plugin-wc/v/2.0.0-ce.0) 🚀 

@keithamus if you could test it on one of your repos, that'd be super helpful. I'll do the same on ours

anyone else lurking around here, also please try it out and let us know any problems!

**Comment by 43081j** [comment]
fyi the ol' npm glob bug caught us out as per usual (they changed how globs work and didn't tell anyone!)

i've updated now and pushed `2.0.0-ce.1` which should work now

**Comment by keithamus** [comment]
https://github.com/github/eslint-plugin-custom-elements has now been archived, with links pointing to this repository. :tada:

Great work @43081j

**Comment by RettentoRectangle** [comment]
We use more than 25 different plugins (in our own monorepo), which are full of overlaps. This is the first time, I think, that two different plugin maintainers have taken the trouble to work together. Keep it up!
